services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 3

  counter-api:
    build:
      context: .
    container_name: counter-api
    ports:
      - "8080:8080"
    environment:
      APP_ENV: test
      REDIS_URL: redis://redis:6379
    depends_on:
      redis:
        condition: service_healthy
